spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnf
    username: root
    password: root
    initialization-mode: always
    
  jpa:
    hibernate:
      ddl-auto: none
      formate_sql: true
      show_sql: true